### ISSUE TITLE
feat: 기초 환경 세팅

### ISSUE THREAD

**Issue by SerenityS** [F-orever/gabozago_APP#1]
## Summary
- 프로젝트를 시작하기에 앞서, 기본적인 환경을 세팅합니다.

## Todo
- [x] 폴더 구조 설정
- [x] 필요 패키지 추가
- [x] const 추가
- [x] 패키지 네임 변경
