### ISSUE TITLE
feat: 메인 홈 View 구현

### ISSUE THREAD

**Issue by SerenityS** [F-orever/gabozago_APP#9]
## Summary
- 메인 홈의 View를 구현합니다.

## Todo
- [x] AppBar, BottomNavigationBar 구현
- [ ] Filter 구현
- [ ] 추천 View 구현
- [ ] 후기 - 게시글 View 구현
- [ ] 후기 - 영상 View 구현
- [ ] 후기 - 숏폼 View 구현
- [ ] 후기 - 사진 View 구현
